### ISSUE TITLE
the pixel value is wrong after read the tiff image created by Fiji

### ISSUE THREAD

**Issue by Chenchao-is-CC** [jmstujenske/Matlab_FastTiffReadWrite#1]
Hello: 
    You coded a great job to faster the tiff reading in matlab. And it is vary fast. But I use bigread4 to load tif image created by Fiji. The matrix is wrong, maybe the data type is wrongly change during tiff reading? And I used matlab function TIFF lib to read the same tiff file, it get the correct pixel.
![Snipaste_2024-03-12_17-22-01_correct_pixel](https://github.com/jmstujenske/Matlab_FastTiffReadWrite/assets/106669478/1a2e29b6-ae35-4078-92bc-753600d4ef90)
![Snipaste_2024-03-12_17-22-36_wrong](https://github.com/jmstujenske/Matlab_FastTiffReadWrite/assets/106669478/bedb4a1f-0063-46a9-85e3-425490b058f9)

**Comment by jmstujenske** [comment]
Hi, can you attach your tiff file so I can figure out what the problem might be?

**Comment by Chenchao-is-CC** [comment]
Thank you very much. The attched file function doesn't support the tif file format. So I am so sory for  having not idea to upload the tiff file.

**Comment by jmstujenske** [comment]
Unfortunately it seems that github doesn't support tiff file attachments. Please email to Stujenske.Lab@gmail.com

**Comment by jmstujenske** [comment]
This has been fixed. The problem was in the memory_map_tiff function-- the offset needed to be decreased by one. I apologize for this mistake. I am puzzled about why this problem never arose for me before. I will track down in the pushes to see if this error was introduced at some point. I appreciate you bringing this to my attention.

**Comment by jmstujenske** [comment]
The problem is that memmapfile (called by memory_map_tiff, which is called by bigread4 as a quick reading method) cannot handle big-endian data. The file that you sent me is big-endian as saved by Fiji. Having not tested this on big-endian tiffs prior to now, I did not pick up on this error. Memory_map_tiff now emits an error if the data is big-endian, and bigread4 now will read these files using the quick fread methods that it already contains. Thanks for bringing this to my attention.
